### ISSUE TITLE
xpath changes

### ISSUE THREAD

**Issue by bharathgs** [ONLPS/IndianNewsSpiders#18]
the current xpath's on the master can be improved.
@AnjanaRita  please update the XPath for all the spiders, except HuffPost wherever necessary.

**Comment by bharathgs** [comment]
- [ ] firstpost

- [ ] wire

- [ ] opindia

- [ ] dailyo

- [ ] catchnews

- [ ] scroll

- [ ] quintnews

**Comment by AnjanaRita** [comment]
No it's working fine

**Comment by bharathgs** [comment]
thanks @AnjanaRita I'm closing this issue, assuming all the xpath related work is done?
